parameters:
#    general_login.example.class: General\LoginBundle\Example

services:
#    general_login.example:
#        class: %general_login.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
